export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILDED = "FETCH_DATA_FAILDED";

export const SEARCH_RESULT = "SEARCH_RESULT";

export const SORT_ASC_RESULT = "SORT_ASC_RESULT";
export const SORT_DESC_RESULT = "SORT_DESC_RESULT";